### ISSUE TITLE
Анафема и зарница паладина

### ISSUE THREAD

**Issue by TimurLyashev** [OLDodin/UniverseMeter#1]
Анафема и зарница записываются в один источник дамага, в таблице отображается тот источник (анафема или зарница), который первым продамажил в бою.

commit  b7c9b2fec006e441427557cf7d0f4d557cf4bc75

**Comment by OLDodin** [comment]
Не наблюдаю такой проблемы. Анафема, Анамефа "интердикт" и зарница отдельно записываются. Идентификатором служит название умения, потому зарница слиться с анафемой не могут.
Если вы с тестового сервера, то там зарница больше не бьет по соло цели, только вокруг текущего таргета

**Comment by TimurLyashev** [comment]
https://youtu.be/9h-OnCm3u1c

Бой начинаю с зарницы, затем вешаю анафему и бью, не используя зарницу. Видно, как дамаг с анафемы растёт.

Второй подход - начинаю с анафемы и бью, не продляя и не переиспользуя анафему (получаю зарницу через "ярость света").

На тестовом сервере ситуация аналогичная - для теста начинал бой с паком мобов с анафемы, далее бил только зарницей.

**Comment by OLDodin** [comment]
Вы для тестового сервера сами перекомпилили скрипты?
У вас точно не какая-то модифицированная версия? Ни на тестовом, и на боевых нашёл твина-пала для теста - не воспроизводится проблема.

**Comment by OLDodin** [comment]
Единственный вариант по коду выходит что в TUMeter.lua в GetInfoFromCache - на строке 151 движок игры возвращает что ресурсные ид анафемы и зарницы одинаковы (но тогда бы это воспроизводилось и у меня). 
Попробуйте за комментировать там же цикл на строках 150-154 и что будет без него?

**Comment by TimurLyashev** [comment]
Для тестового сервера используется версия, которую выложили разработчики (на основе 2.4.1).
Для "боевого" сервера я клонирую репозиторий аддона в папку и периодически произвожу pull изменений из github, потому модификаций там нет. Версия 3.0.1.

**Comment by OLDodin** [comment]
Судя по видео вы на подписочном сервере. 
Вы сможете сделать правки кода, описанные выше или вам скинуть pak файлы для теста. Возможно ИД этих умений сломаны на подписочных серверах.

**Comment by TimurLyashev** [comment]
Протестировал правки -- изменений нет, анафема и зарница склеиваются. На другом устройстве даже без правок баг не воспроизводится.

**Comment by OLDodin** [comment]
Если на другом всё ок - то сносите всю папку с аддоном и качайте заново, может где-то что-то. 
Не поможет на строке 193 (TUMeter.lua) добавьте
userMods.SendSelfChatMessage(userMods.ToWString(spellInfo.NameStr), "notice")
В чат будет скидывать имя умения от которого регается урон.

**Comment by OLDodin** [comment]
Вот сам собрал две версии UniverseMeter1.pak и UniverseMeter2.pak
https://mega.nz/file/fsN2HLyR#d0DypKb9VTwdKNJMIH3KeXbDXcjVm5X8_SbhP7LKu-0
https://mega.nz/file/Kh1mgALZ#2d6yVPvzyLzDs6Ob4p6DcByZaUrQ9EdbACjh43UqhVY
Обе выводят в чат 1я без кэша по ИД, 2я с кэшем.

**Comment by TimurLyashev** [comment]
В обоих случаях анафема и зарница "склеены":

 - <details><summary>UniverseMeter1.pak</summary>
       <img src="https://github.com/OLDodin/UniverseMeter/assets/29640851/bf660261-5ee9-4412-99b6-f3f56c73abd3">
   </details>

  - <details><summary>UniverseMeter2.pak</summary>
     <img src="https://github.com/OLDodin/UniverseMeter/assets/29640851/b9c38090-d820-4477-93a3-defad086a330)">
   </details>

**Comment by OLDodin** [comment]
А когда одна анафема в статистике, зарница в чат печатается (или наоборот)?

**Comment by TimurLyashev** [comment]
Сложно сказать - на скриншотах видно, что символы отображаются как '?', а количество символов в словах "анафема" и "зарница" одинаковое.

**Comment by OLDodin** [comment]
А где скриншоты?

**Comment by OLDodin** [comment]
В самой винде. Параметры - время и язык - язык - административные языковые параметры - Дополнительно - язык программ не поддерживающих юникод - там что стоит?
И каков язык самой системы

**Comment by TimurLyashev** [comment]
Скриншоты:
 - <details><summary>Анафема</summary>
       <img src="https://github.com/OLDodin/UniverseMeter/assets/29640851/88a46b27-52af-4239-aace-7ca23738cc71">
   </details>

  - <details><summary>Зарница</summary>
     <img src="https://github.com/OLDodin/UniverseMeter/assets/29640851/9d945d40-f91d-41b4-aecc-fa317356c6d2)">
   </details>

Язык системы и язык программ, не поддерживающих юникод -- английский (американский). Сейчас попробую поменять.

**Comment by OLDodin** [comment]
Причина тогда ясна, смена языка поможет. Подумаю как переделать ИД раз не только для ресурсов, но и для внутренних строк движка игры зависимость от этой настройки.

**Comment by TimurLyashev** [comment]
Активировал вот этот чекбокс и заработало без смены локали:
![изображение](https://github.com/OLDodin/UniverseMeter/assets/29640851/6af90b8c-ff7a-4298-94c1-cd0d40899741)

Спасибо.

**Comment by OLDodin** [comment]
Если что выложил фикс. Можно будет и не менять эту настройку в винде
